### ISSUE TITLE
Broken for julia 0.4

### ISSUE THREAD

**Issue by rwgardner2** [JuliaGeo/Geodesy.jl#30]
Most of the source files are gone.  There is no LLAfromECEF, for example.  Maybe the intent is no longer to support julia < 0.5.  If so, that should be made explicit with a failed installation/update.

**Comment by rwgardner2** [comment]
Well, interestingly, if I explicitly add VersionNumber 0.0.2, it works.  Normal Pkg.add() was giving me 0.0.1, possibly because of some dependency complications?  Adding v0.0.2 downgraded my Compat and my CoordinateTransformations.

**Comment by c42f** [comment]
Geodesy-0.0.1 had a completely different API, so if Pkg decides to install that due to a version clash, you'll certainly be confused!  However, Geodesy-0.2.0 is documented to work with julia-0.4 and should be installable with a reasonably similar API to the latest version.

Generally speaking, I'd strongly encourage you to move to julia-0.5 if you have the option, as some of the dependencies (`CoordinateTransformations` and `StaticArrays` vs `FixedSizeArrays`) have moved on considerably since 0.4, and more importantly the base language has improved a lot.  Personally I've found that porting code from 0.4 to 0.5 has generally been fairly easy and worthwhile :-)

**Comment by andyferris** [comment]
Agreed.

**Comment by andyferris** [comment]
I'm a bit confused though, you should be using v0.2.0 not v0.0.2.

**Comment by andyferris** [comment]
Not sure why your package manager downgraded some packages - it might be unrelated to Geodesy, I dunno.

**Comment by c42f** [comment]
Yes, the package manager should have installed 0.2.0, I'm not sure why it didn't.  Sometimes if there's complex interdependencies between a set of three or more packages, `Pkg` resolves the problem in a way which is surprising to users.

**Comment by c42f** [comment]
I'm not sure what more we can do here so I'm going to close this. Please feel free to reopen if we've missed something.
