### ISSUE TITLE
LatLon(missing, missing) triggers a stack overflow error

### ISSUE THREAD

**Issue by austinlostinboston** [JuliaGeo/Geodesy.jl#47]
This doesn't seem like an intended result for passing `missing` to `LatLon`. At the very least, this should trigger an internal exception within Geodesy. There also might be a greater question of whether a `LatLon(missing, missing)` should be allowed to exist.

    julia> LatLon(missing, missing)
    ERROR: StackOverflowError:
    Stacktrace:
    [1] LatLon(::Missing, ::Missing) at /Users/my_name/.julia/packages/Geodesy/qjth5/src/points.jl:37     (repeats 80000 times)

**Comment by visr** [comment]
https://github.com/JuliaGeo/Geodesy.jl/blob/277463183419b73f73ae4f68cd1a8d7798845165/src/points.jl#L33-L37

Oh that's not so nice behavior.
Since `missing` is not a `Number`, it is not supported in `LatLon` currently. But when you try it, it calls the method with `promote`, which, since the result is still not two identical subtypes of `Number`, calls itself again and again, leading to the `StackOverflowError`. Same happens for `LatLon('a', 'b')` for instance.

I'm guessing that method should also be restricted to `Number` types:

```julia
LatLon(lat::Number, lon::Number) = LatLon(promote(lat, lon)...)
```

**Comment by andyferris** [comment]
> I'm guessing that method should also be restricted to `Number` types

Yes, for the short term, let's do that!

@austinlostinboston For the moment, you might have better luck considering thet `LatLon` as an "entire" object that may be missing, i.e. model your data with `Union{Missing, LatLon{Float64}}` or whatever.

**Comment by austinlostinboston** [comment]
All good suggestions and thanks for the help @visr and @andyferris!
