### ISSUE TITLE
Incorrect conversion from ECEF to LLA with small radii and WGS84-type flattening

### ISSUE THREAD

**Issue by anowacki** [JuliaGeo/Geodesy.jl#50]
Attempting to convert ECEF coordinates to lon-lat leads to very large errors in the latitude when the point is at a radius less than ~5e^4 m, z is small, and when flattening is similar to WGS84's ellipsoid's value.

(See #49 for a necessary fix before this can be attempted.)

As an example, take a geocentric point pointing along X:

```julia
julia> using Geodesy

julia> p = LLA(ECEF(1, 0, 0), wgs84)
LLA(lat=89.99866260444664°, lon=0.0°, alt=-6.356752314233508e6)

julia> ∆alt = -p.alt - (ellipsoid(wgs84).a - 1)
-21383.68576649204
```

By definition of the ECEF frame, the correct answer is `lat=0°, lon=0°, alt=(ellipsoid(wgs84).a - 1)`, and `∆alt` should be 0 m, not -21 km.

~I haven't had the time to learn the C++ interface (or indeed, learn C++!) to GeographicLib to check this against the original implementation of the transform, but~ [The C++ GeographicLib has apparently the same problem.] I have checked and Proj (called via Python) gets this right:

```julia
julia> using PyCall

julia> pyproj = pyimport("pyproj"); # version 2.2.1

julia> py_ecef = pyproj.Proj(proj="geocent", ellps="WGS84", datum="WGS84");

julia> py_lla = pyproj.Proj(proj="latlon", ellps="WGS84", datum="WGS84");

julia> lon, lat, alt = pyproj.transform(py_ecef, py_lla, 1, 0, 0, radians=false)
(0.0, 0.0, -6.378136e6)

julia> -alt - (ellipsoid(wgs84).a - 1)
0.0
```

Testing a range of values shows the answer is only right at x ≈ 4.27e4 m:
```julia
julia> using Plots

julia> plot(x->LLA(ECEF(0, x, 0), wgs84).lat, 0, 5e4, xlabel="x / m", ylabel="'Latitude' / °")
```

![fig](https://user-images.githubusercontent.com/1231209/64462836-c0b48180-d0f9-11e9-9910-d20f528162bd.png)

More importantly, this is 0.0067 of the semimajor radius for WGS84's flattening, which can be confirmed by creating a different ellipsoid (with, say, `Ellipsoid(a="1", f_inv="298.257223563")`).

The same error does not occur for a sphere:

```julia
julia> LLA(ECEF(1e-6, 0, 0), Ellipsoid(a="1", b="1"))
LLA(lat=0.0°, lon=0.0°, alt=-0.999999)
```

It's fair to ask why one cares about doing this within 40 km of the centre of the Earth, but it's still disconcerting, and if Proj can get it right then I think it would be good for Geodesy.jl to do so to.

**Comment by c42f** [comment]
I don't have time to look closely right now, but note that you can use the GeographicLib command line tools: https://geographiclib.sourceforge.io/html/utilities.html  I think you want CartConvert?

**Comment by anowacki** [comment]
I have (approximately) verified that the same behaviour occurs in the original C++ version.  I have opened a [forum post](https://sourceforge.net/p/geographiclib/discussion/1026621/thread/2bd2192fd7/) at the GeographicLib SourceForge site.  So I guess coordinating any fix with Charles Karney makes sense.

**Comment by cffk** [comment]
I'm just pasting in the answer I provided for the C++ library, GeographicLib.  Basically LLAfromECEF is working as advertised.

Geocentric::Inverse is behaving correctly!  (I assume you mean Geocentric::Reverse instead of Geocentric::Inverse?) The geocentric coordinates

    1 0 0

correspond to 4 possible sets of geodetic coordinates

    89.998662604446636 0 -6356752.314233507
    -89.998662604446636 0 -6356752.314233507
    0 0 -6378136
    0 180 -6378138

You can check this with

    CartConvert -p 20 <<EOF
    89.998662604446636 0 -6356752.314233507
    -89.998662604446636 0 -6356752.314233507
    0 0 -6378136
    0 180 -6378138
    EOF

The documentation for Geocentric::Reverse states: "In general there are multiple solutions and the result which maximizes *h* is returned. If there are still multiple solutions with different latitudes (applies only if *Z* = 0), then the solution with *lat* > 0 is returned."  Applying these rules to the possible solutions yields

    89.998662604446636 0 -6356752.314233507

Let me know if you have any questions.

**Comment by cffk** [comment]
Incidentally, a related complaint I have to handle about 4 times a year is "why is the distance from (lat,lon) = (0,0) to (0,179.5) wrong?"  The answer is that the *shortest* distance in this case is *not* along the equator.

**Comment by c42f** [comment]
Thanks @cffk. Every time I look at GeographicLib (the C++ version) I appreciate the numerical craftsmanship there.

Incidentally @anowacki, I've always thought it would be ideal to be able to call the real GeographicLib from julia. It turns out that Cxx is now quite easy to install using the normal package system (at least on linux) so you can call any part of GeographicLib directly from the REPL. For example your geocentric test case:

```julia
using Cxx
using Libdl

# Workaround weird issue with dynamic linking
Libdl.dlopen("/usr/lib/x86_64-linux-gnu/libGeographic.so", Libdl.RTLD_GLOBAL)

cxx"""
#include <GeographicLib/Constants.hpp>
#include <GeographicLib/Geocentric.hpp>

using namespace GeographicLib;
"""

earth = icxx"Geocentric(Constants::WGS84_a(), Constants::WGS84_f());"

lat,lon,h = Ref(0.0), Ref(0.0), Ref(0.0)
@cxx earth->Reverse(1, 0, 0, lat, lon, h)

@show lat[] lon[] h[]

x,y,z = Ref(0.0),Ref(0.0),Ref(0.0)
@cxx earth->Forward(lat[],lon[],h[], x,y,z)

@show x[] y[] z[]
```

**Comment by anowacki** [comment]
Thank you, @cffk, for the explanation in the other thread.  Chris, thanks for attending to this quickly.  I agree that Geodesy.jl is showing the desired behaviour.

Would you be amenable to a PR adding some of the explanation from GeographicLib's documentation to explain this behaviour in a docstring and/or `README.md`?  Seems like if it prevents other people jumping to conclusions like I did, it might make everyone's lives easier.

II don't know whether another choice reagarding which of the multiple solutions to the transformation in this example is equally sensible (perhaps Charles can chip in), but if so, then making Geodesy's choice (per GeographicLIb's choice) explicit would probably be necessary as well as desirable.

**Comment by c42f** [comment]
Documentation improvements are always welcome!

**Comment by cffk** [comment]
GeographicLib's implementation of Geocentric::Reverse could be modified to give all the possible solutions.  However, it's a few years since I thought about this, so I'm not inclined to pursue this without some reasonable use case.  The "maximum *h*" solution provided has the advantage that it's unambiguous (even if it sometimes catches people off guard).

Again there's a parallel issue with GeographicLib's Geodesic::Inverse. For approximately antipodal points, there may be 2 or 4 solutions of about the same length.  However, I've seen no reason why Geodesic::Inverse shouldn't just return the shortest one.
